version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.4
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pg:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}

volumes:
  pgdata:
