version: '3.4'

services:
  equipoback-dev:
    image: equipoback
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./api:/home/appuser/api
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - 8000:8000
    stdin_open: true

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
