# Generated by Django 4.0.3 on 2022-06-23 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
            ],
            options={
                'verbose_name': 'TypeService',
                'verbose_name_plural': 'TypeServices',
                'db_table': 'TypeService',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.typeservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'Appointment',
                'ordering': ('id',),
            },
        ),
    ]
